[package]
name = "mcsr-ranked-api"
version = "0.1.0"
edition = "2021"

[lib]
name = "mcsr_ranked_api"
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_repr = "0.1.19"
uuid = { version = "1.11.0", features = ["serde"] }
